name: go testing
on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./... -v -covermode=count
      - name: install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest
      - name: Run benchmarks
        run: go test ./... -bench . -count 10 -shuffle on > benchstat.out && benchstat benchstat.out
  
  # publish-benchmarks:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: checkout
  #     uses: actions/checkout@v2
  #   - name: gobenchdata publish
  #     uses: bobheadxi/gobenchdata@v1
  #     with:
  #       PRUNE_COUNT: 30
  #       GO_TEST_FLAGS: -cpu 1,2
  #       PUBLISH: true
  #       PUBLISH_BRANCH: gh-pages
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}