name: go testing
on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: go test ./... -v -covermode=count

  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest
      - name: Run benchmarks
        run: go test ./... -bench . -shuffle on -count 10 | tee benchoutput.txt
      - name: Display benchmark output
        run: benchstat benchoutput.txt
  
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
