name: benchmark on master
# Do not run this workflow on pull request since this workflow has permission to modify contents.
on:
  push:
    branches:
      - master

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - name: Run deps benchmarks
        run: go test github.com/jamesjarvis/massivelyconcurrentsystems/deps -bench . -shuffle on -benchtime 10s | tee depsoutput.txt
      - name: Store deps benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          # Where the output from the benchmark tool is stored
          output-file-path: depsoutput.txt
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          # Mention @jamesjarvis in the commit comment
          alert-comment-cc-users: '@jamesjarvis'
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          # Where to store the bench results.
          benchmark-data-dir-path: 'bench/deps'
      - name: Run pool benchmarks
        run: go test github.com/jamesjarvis/massivelyconcurrentsystems/pool -bench . -shuffle on -benchtime 10s | tee pooloutput.txt
      - name: Store pool benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          # Where the output from the benchmark tool is stored
          output-file-path: pooloutput.txt
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          # Mention @jamesjarvis in the commit comment
          alert-comment-cc-users: '@jamesjarvis'
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          # Where to store the bench results.
          benchmark-data-dir-path: 'bench/pool'
